HAI 1.2
I HAS A NUMBER ITZ 0
IM IN YR LOOPY UPPIN YR NUMBER TIL BOTH SAEM NUMBER AN 101
    NUMBER R SUM OF NUMBER AN 1 
    BOTH SAEM MOD OF NUMBER AN 15 AN 1
    O RLY?
        YA RLY
            VISIBLE  "fizzbuzz"
        MEBBE BOTH SAEM MOD OF NUMBER AN 5 AN 1
            VISIBLE  "fizz"
        MEBBE BOTH SAEM MOD OF NUMBER AN 3 AN 1
            VISIBLE  "buzz"
        NO WAI
            VISIBLE NUMBER
    OIC
IM OUTTA YR LOOPY

KTHXBYE
